-- Execute this script in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Profiles are visible to their owner" on public.profiles;
create policy "Profiles are visible to their owner"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Anyone can submit a contact message" on public.contact_messages;
create policy "Anyone can submit a contact message"
  on public.contact_messages for insert
  with check (true);


-- =====================================================================
-- Rôles : seuls les profils « admin » ou « agent » accèdent au tableau de bord.
-- Après avoir créé votre compte, donnez-vous le rôle admin :
--   update public.profiles set role = 'admin'
--   where id = (select id from auth.users where email = 'votre@email.com');
-- =====================================================================
alter table public.profiles add column if not exists role text not null default 'visiteur'
  check (role in ('visiteur', 'agent', 'admin'));

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('agent', 'admin'));
$$;

drop policy if exists "Staff can read contact messages" on public.contact_messages;
create policy "Staff can read contact messages"
  on public.contact_messages for select
  using (public.is_staff());

-- Empêche un utilisateur de s'attribuer lui-même un rôle.
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id and role = (select p.role from public.profiles p where p.id = auth.uid()));

-- =====================================================================
-- Campagne agricole : campagnes, lots de semences, distributions
-- =====================================================================
create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  start_date date not null,
  end_date date not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.seed_lots (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  lot_number text not null unique,
  species text not null check (species in ('arachide', 'mais', 'niebe', 'mil', 'sorgho')),
  variety text not null,
  category text not null check (category in ('Prébase', 'Base', 'R1', 'R2')),
  quantity_kg numeric(12, 2) not null check (quantity_kg > 0),
  warehouse text not null,
  region text not null,
  certification_date date,
  germination_rate numeric(5, 2) check (germination_rate between 0 and 100),
  status text not null default 'en_attente' check (status in ('certifie', 'en_attente', 'rejete')),
  created_at timestamptz not null default now()
);

create table if not exists public.distributions (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  lot_id uuid not null references public.seed_lots(id) on delete restrict,
  distributed_on date not null default current_date,
  beneficiary_name text not null,
  beneficiary_type text not null check (beneficiary_type in ('agriculteur', 'cooperative', 'gie', 'autre')),
  phone text,
  region text not null,
  department text,
  commune text,
  quantity_kg numeric(12, 2) not null check (quantity_kg > 0),
  area_ha numeric(10, 2),
  mode text not null default 'subvention' check (mode in ('subvention', 'vente', 'don')),
  unit_price numeric(12, 2),
  created_by uuid default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists distributions_campaign_idx on public.distributions(campaign_id);
create index if not exists distributions_lot_idx on public.distributions(lot_id);

-- Refuse une distribution qui dépasse le stock restant du lot.
create or replace function public.check_lot_stock()
returns trigger
language plpgsql
as $$
declare
  stock numeric;
  used numeric;
begin
  select quantity_kg into stock from public.seed_lots where id = new.lot_id for update;
  select coalesce(sum(quantity_kg), 0) into used from public.distributions
    where lot_id = new.lot_id and id is distinct from new.id;
  if used + new.quantity_kg > stock then
    raise exception 'Stock insuffisant pour ce lot (reste % kg)', stock - used;
  end if;
  return new;
end;
$$;

drop trigger if exists distributions_check_stock on public.distributions;
create trigger distributions_check_stock
before insert or update on public.distributions
for each row execute procedure public.check_lot_stock();

alter table public.campaigns enable row level security;
alter table public.seed_lots enable row level security;
alter table public.distributions enable row level security;

drop policy if exists "Staff manage campaigns" on public.campaigns;
create policy "Staff manage campaigns" on public.campaigns
  for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Staff manage seed lots" on public.seed_lots;
create policy "Staff manage seed lots" on public.seed_lots
  for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Staff manage distributions" on public.distributions;
create policy "Staff manage distributions" on public.distributions
  for all using (public.is_staff()) with check (public.is_staff());

-- Vérification publique d'un lot (traçabilité) : n'expose que des informations non sensibles.
create or replace function public.verify_lot(p_lot_number text)
returns table (
  lot_number text, species text, variety text, category text,
  certification_date date, germination_rate numeric, status text, campaign text
)
language sql
stable
security definer set search_path = public
as $$
  select l.lot_number, l.species, l.variety, l.category,
         l.certification_date, l.germination_rate, l.status, c.name
  from public.seed_lots l
  join public.campaigns c on c.id = l.campaign_id
  where upper(l.lot_number) = upper(trim(p_lot_number))
  limit 1;
$$;

grant execute on function public.verify_lot(text) to anon, authenticated;

-- =====================================================================
-- Formulaires publics : réservations de semences et demandes de partenariat
-- =====================================================================
create table if not exists public.seed_reservations (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  region text not null,
  commune text,
  species text not null,
  quantity_kg numeric(12, 2) not null check (quantity_kg > 0),
  area_ha numeric(10, 2),
  message text,
  status text not null default 'nouvelle' check (status in ('nouvelle', 'confirmee', 'servie', 'annulee')),
  created_at timestamptz not null default now()
);

create table if not exists public.partnership_requests (
  id uuid primary key default gen_random_uuid(),
  organization text not null,
  contact_name text not null,
  email text not null,
  phone text,
  country text not null,
  partner_type text not null,
  message text not null,
  status text not null default 'nouvelle' check (status in ('nouvelle', 'en_cours', 'conclue', 'refusee')),
  created_at timestamptz not null default now()
);

alter table public.seed_reservations enable row level security;
alter table public.partnership_requests enable row level security;

drop policy if exists "Anyone can reserve seeds" on public.seed_reservations;
create policy "Anyone can reserve seeds" on public.seed_reservations
  for insert with check (status = 'nouvelle');

drop policy if exists "Staff manage reservations" on public.seed_reservations;
create policy "Staff manage reservations" on public.seed_reservations
  for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Anyone can request a partnership" on public.partnership_requests;
create policy "Anyone can request a partnership" on public.partnership_requests
  for insert with check (status = 'nouvelle');

drop policy if exists "Staff manage partnership requests" on public.partnership_requests;
create policy "Staff manage partnership requests" on public.partnership_requests
  for all using (public.is_staff()) with check (public.is_staff());
